// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2lP3JsrGBzbcLD1Sjodb98fBIi7qGr4k',
    appId: '1:575650782773:web:fc41bb112c333271125b7c',
    messagingSenderId: '575650782773',
    projectId: 'chat-taskmanager-app',
    authDomain: 'chat-taskmanager-app.firebaseapp.com',
    storageBucket: 'chat-taskmanager-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXZQVxVS-ofWNBqTCXO3TBeTMPLsShao',
    appId: '1:575650782773:android:f7139ac35cb5a86d125b7c',
    messagingSenderId: '575650782773',
    projectId: 'chat-taskmanager-app',
    storageBucket: 'chat-taskmanager-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXZANaAgtAJfBA3ozp8k6uMkJu1oTLJw',
    appId: '1:575650782773:ios:6658795acb71e725125b7c',
    messagingSenderId: '575650782773',
    projectId: 'chat-taskmanager-app',
    storageBucket: 'chat-taskmanager-app.firebasestorage.app',
    iosBundleId: 'com.example.chatTaskmanagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdXZANaAgtAJfBA3ozp8k6uMkJu1oTLJw',
    appId: '1:575650782773:ios:6658795acb71e725125b7c',
    messagingSenderId: '575650782773',
    projectId: 'chat-taskmanager-app',
    storageBucket: 'chat-taskmanager-app.firebasestorage.app',
    iosBundleId: 'com.example.chatTaskmanagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2lP3JsrGBzbcLD1Sjodb98fBIi7qGr4k',
    appId: '1:575650782773:web:67fceaf316f42832125b7c',
    messagingSenderId: '575650782773',
    projectId: 'chat-taskmanager-app',
    authDomain: 'chat-taskmanager-app.firebaseapp.com',
    storageBucket: 'chat-taskmanager-app.firebasestorage.app',
  );
}
